-- Новая структура: единые радиусы 4 колец + рабочие точки
ALTER TABLE t_p51549197_aqua_terra_project.price_zones
  ADD COLUMN IF NOT EXISTS ring1_km     FLOAT   NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS ring1_factor FLOAT   NOT NULL DEFAULT 1.0,
  ADD COLUMN IF NOT EXISTS ring1_label  VARCHAR(64) DEFAULT 'Рядом',
  ADD COLUMN IF NOT EXISTS ring2_km     FLOAT   NOT NULL DEFAULT 25,
  ADD COLUMN IF NOT EXISTS ring2_factor FLOAT   NOT NULL DEFAULT 1.3,
  ADD COLUMN IF NOT EXISTS ring2_label  VARCHAR(64) DEFAULT 'Недалеко',
  ADD COLUMN IF NOT EXISTS ring3_km     FLOAT   NOT NULL DEFAULT 45,
  ADD COLUMN IF NOT EXISTS ring3_factor FLOAT   NOT NULL DEFAULT 1.6,
  ADD COLUMN IF NOT EXISTS ring3_label  VARCHAR(64) DEFAULT 'Далеко',
  ADD COLUMN IF NOT EXISTS ring4_km     FLOAT   NOT NULL DEFAULT 70,
  ADD COLUMN IF NOT EXISTS ring4_factor FLOAT   NOT NULL DEFAULT 2.0,
  ADD COLUMN IF NOT EXISTS ring4_label  VARCHAR(64) DEFAULT 'Очень далеко',
  ADD COLUMN IF NOT EXISTS work_points  JSONB   DEFAULT '[]'::jsonb;
